### ISSUE TITLE
Crashes when below 10c

### ISSUE THREAD

**Issue by TwinUsers** [gzachos/rpi-airtemp#1]
Hello,

This script works well when temperature is above 10c, however anything below and it crashes stating awk error on line = 

File temp_sensor.sh

SENSOR_TEMP=$(awk "BEGIN{print ${RAW_DATA:(-5)}/1000}")

I believe it's this line affecting it. Any chance of a fix

**Comment by gzachos** [comment]
Thanks for the notice. Everything should work now!
