### ISSUE TITLE
two sensors 

### ISSUE THREAD

**Issue by TwinUsers** [gzachos/rpi-airtemp#4]
could a second sensor be graphed with the first? rather than having to use another rpi??

I've got two sensors but can't graph second.

**Comment by gzachos** [comment]
Generally speaking, yes. Currently, this implementation doesn't support multiple sensors. I have implemented the display of two sensors in [aeolus-logger](https://github.com/gzachos/aeolus-logger) but those sensors has always a constant difference ([photo](https://raw.githubusercontent.com/gzachos/aeolus-logger/master/images/demo_temp_1hour_dual.png)) which plays an important role in graph readability.
